version: '3'

services:
  message-service:
    image: hub.mooc.com:10000/micro-service/message-service:latest

  user-service:
    image: hub.mooc.com:10000/micro-service/user-service:latest
    command:
    - "--mysql.address=192.168.202.1"

  user-edge-service:
    image: hub.mooc.com:10000/micro-service/user-edge-service:latest
    links:
    - user-service
    - message-service
    command:
    - "--redis.address=192.168.202.61"
    - "--redis.port=7001"
    ports:
    - 8082:8082

  course-service:
    image: hub.mooc.com:10000/micro-service/course-service:latest
    links:
    - user-service
    command:
    - "--mysql.address=192.168.202.1"
    - "--zookeeper.address=192.168.202.61:2181?backup=192.168.202.62:2181,192.168.202.63:2181"

  course-edge-service:
    image: hub.mooc.com:10000/micro-service/course-edge-service:latest
    links:
    - user-edge-service
    command:
    - "--zookeeper.address=192.168.202.61:2181?backup=192.168.202.62:2181,192.168.202.63:2181"
    ports:
    - 8081:8081

  api-gateway-zuul:
    image: hub.mooc.com:10000/micro-service/api-gateway-zuul:latest
    links:
    - user-edge-service
    - course-edge-service
    ports:
    - 8888:8888
